# Generated by Django 4.1.4 on 2023-08-18 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(blank=True, default='no_product_img.png', null=True, upload_to='core_images'),
        ),
    ]
