# Generated by Django 4.1.4 on 2023-08-25 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_order_ref_coe'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='ref_coe',
            new_name='ref_code',
        ),
    ]
