# Generated by Django 4.1.4 on 2023-09-06 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_refund'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
