# Generated by Django 4.2.5 on 2023-09-16 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_code',
            field=models.CharField(default='fgd63954dcvb2s9g3e2v', max_length=20),
            preserve_default=False,
        ),
    ]
