# Generated by Django 4.2.5 on 2023-09-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_order_refund_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ref_code',
        ),
        migrations.AddField(
            model_name='order',
            name='session_id',
            field=models.CharField(default='', max_length=66),
        ),
    ]
