# Generated by Django 4.2.5 on 2023-09-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_remove_order_ref_code_order_session_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='intent_id',
            field=models.CharField(default='', max_length=27),
        ),
    ]
