# Generated by Django 4.2.5 on 2023-09-16 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order_intent_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='intent_id',
            field=models.CharField(max_length=27),
        ),
    ]
