# Generated by Django 4.2.5 on 2023-09-16 22:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_alter_order_session_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='intent_id',
            new_name='payment_intent_id',
        ),
    ]
