# Generated by Django 4.2.5 on 2023-09-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_rename_intent_id_order_payment_intent_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='refund_granted',
        ),
        migrations.RemoveField(
            model_name='order',
            name='refund_requested',
        ),
    ]
