# Generated by Django 4.2.5 on 2023-09-18 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_order_refund_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='refund_accepted',
            new_name='refund_status',
        ),
    ]
