# Generated by Django 4.2.5 on 2023-09-20 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_rename_refund_accepted_order_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='done_ordered_time',
            field=models.DateTimeField(default='2023-11-11 11:11:11'),
            preserve_default=False,
        ),
    ]
